import type { UnifiedColumnDef, UnifiedColumnKey } from "./types";

export function buildAllColumns(t: (key: string, fallback?: string) => string): UnifiedColumnDef[] {
  return [
    { key: "name", label: t("budget.name"), width: "w-[260px]", editType: "none", appliesTo: "both" },
    { key: "rowType", label: t("unifiedTable.type"), width: "w-[90px]", editType: "none", appliesTo: "both" },
    { key: "status", label: t("common.status"), width: "w-[160px]", editType: "select", appliesTo: "both" },
    { key: "priority", label: t("tasks.priority"), width: "w-[100px]", extra: true, editType: "select", appliesTo: "task" },
    { key: "budget", label: t("common.budget"), width: "w-[120px]", align: "right", extra: true, editType: "numeric", appliesTo: "both" },
    { key: "ordered", label: t("budget.ordered"), width: "w-[120px]", align: "right", extra: true, editType: "numeric", appliesTo: "both" },
    { key: "paid", label: t("budget.paid"), width: "w-[120px]", align: "right", extra: true, editType: "numeric", appliesTo: "both" },
    { key: "remaining", label: t("unifiedTable.remaining"), width: "w-[120px]", align: "right", extra: true, editType: "none", appliesTo: "both" },
    { key: "room", label: t("budget.room", "Room"), width: "w-[120px]", extra: true, editType: "select", appliesTo: "both" },
    { key: "assignee", label: t("tasks.assignee"), width: "w-[150px]", extra: true, editType: "select", dbField: "assigned_to_stakeholder_id", appliesTo: "task" },
    { key: "costCenter", label: t("tasks.costCenter"), width: "w-[140px]", extra: true, editType: "select", dbField: "cost_center", appliesTo: "both" },
    { key: "startDate", label: t("common.startDate"), width: "w-[140px]", extra: true, editType: "date", dbField: "start_date", appliesTo: "task" },
    { key: "finishDate", label: t("common.finishDate"), width: "w-[140px]", extra: true, editType: "date", dbField: "finish_date", appliesTo: "task" },
    { key: "dueDate", label: t("tasksTable.dueDate", "Due date"), width: "w-[140px]", extra: true, editType: "date", dbField: "due_date", appliesTo: "task" },
    { key: "progress", label: t("tasks.progress"), width: "w-[120px]", extra: true, editType: "progress", appliesTo: "task" },
    { key: "paymentStatus", label: t("tasksTable.paymentStatus", "Payment status"), width: "w-[140px]", extra: true, editType: "select", dbField: "payment_status", appliesTo: "task" },
    { key: "estimatedHours", label: t("tasksTable.estimatedHours", "Est. hours"), width: "w-[110px]", align: "right", extra: true, editType: "numeric", dbField: "estimated_hours", appliesTo: "task" },
    { key: "hourlyRate", label: t("tasksTable.hourlyRate", "Hourly rate"), width: "w-[110px]", align: "right", extra: true, editType: "numeric", dbField: "hourly_rate", appliesTo: "task" },
    { key: "subcontractorCost", label: t("tasksTable.subcontractorCost", "Subcontractor"), width: "w-[130px]", align: "right", extra: true, editType: "numeric", dbField: "subcontractor_cost", appliesTo: "task" },
    { key: "materialEstimate", label: t("tasksTable.materialEstimate", "Material est."), width: "w-[130px]", align: "right", extra: true, editType: "numeric", dbField: "material_estimate", appliesTo: "task" },
    { key: "markupPercent", label: t("tasksTable.markupPercent", "Markup %"), width: "w-[110px]", align: "right", extra: true, editType: "numeric", dbField: "markup_percent", appliesTo: "task" },
    { key: "vendorName", label: t("unifiedTable.vendorName"), width: "w-[150px]", extra: true, editType: "none", appliesTo: "material" },
    { key: "quantity", label: t("unifiedTable.quantity"), width: "w-[100px]", align: "right", extra: true, editType: "none", appliesTo: "material" },
    { key: "attachment", label: t("common.attachment", "Attachment"), width: "w-[80px]", extra: true, editType: "none", appliesTo: "both" },
    { key: "actions", label: t("common.actions"), width: "w-[60px]", editType: "none", appliesTo: "both" },
  ];
}

export const TASK_DB_FIELD_MAP: Partial<Record<UnifiedColumnKey, string>> = {
  name: "title",
  budget: "budget",
  ordered: "ordered_amount",
  paid: "paid_amount",
  status: "payment_status",
  priority: "priority",
  room: "room_id",
  assignee: "assigned_to_stakeholder_id",
  costCenter: "cost_center",
  startDate: "start_date",
  finishDate: "finish_date",
  dueDate: "due_date",
  progress: "progress",
  paymentStatus: "payment_status",
  estimatedHours: "estimated_hours",
  hourlyRate: "hourly_rate",
  subcontractorCost: "subcontractor_cost",
  materialEstimate: "material_estimate",
  markupPercent: "markup_percent",
};

export const MATERIAL_DB_FIELD_MAP: Partial<Record<UnifiedColumnKey, string>> = {
  name: "name",
  budget: "price_total",
  ordered: "ordered_amount",
  paid: "paid_amount",
  status: "status",
  room: "room_id",
  costCenter: "cost_center",
};

export const SORT_FIELD_MAP: Partial<Record<UnifiedColumnKey, string>> = {
  name: "name",
  rowType: "rowType",
  status: "status",
  priority: "priority",
  budget: "budget",
  ordered: "ordered",
  paid: "paid",
  room: "room",
  assignee: "assignee",
  costCenter: "costCenter",
  startDate: "startDate",
  finishDate: "finishDate",
  dueDate: "dueDate",
  progress: "progress",
  paymentStatus: "paymentStatus",
  estimatedHours: "estimatedHours",
  hourlyRate: "hourlyRate",
  subcontractorCost: "subcontractorCost",
  materialEstimate: "materialEstimate",
  markupPercent: "markupPercent",
  vendorName: "vendorName",
  quantity: "quantity",
};
